version: '3.7'

services:
  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres:12.3
    volumes:
      - postgres_auth-vincelivemix:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_auth-vincelivemix: {}
